import { Flex } from "@chakra-ui/react";
import Head from "next/head";
import { useState } from "react";
import { Header, Lists, Map } from "../components";

export default function Home() {
  const [coordinates, setCoordinates] = useState({ lat: 0, lng: 0 });
  const [type, setType] = useState("restaurants");
  const [ratings, setRatings] = useState("");
  return (
    <>
      <Head>
        <title>Travel Advisor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex
        justifyContent={"center"}
        alignItems={"center"}
        width={"100vw"}
        maxWidth={"100vw"}
        height={"100vh"}
        maxHeight="100vh"
      >
        <Header
          ratings={ratings}
          setRatings={setRatings}
          type={type}
          setType={setType}
        />
        {/* <Lists /> */}
        <Map coordinates={coordinates} setCoordinates={setCoordinates} />
      </Flex>
    </>
  );
}
